routes/web.php
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\AeropuertoController;
use App\Http\Controllers\BancosController;
use App\Http\Controllers\ClasificacionController;
use App\Http\Controllers\ContenedorController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\EmailsController;
use App\Http\Controllers\EntidadesBancoController;
use App\Http\Controllers\EntidadesController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\OperacionController;
use App\Http\Controllers\OperacionDetalleController;
use App\Http\Controllers\OperationDetailsController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\CargoController;
use App\Http\Controllers\ConteinerReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes([
	'register' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('posts', PostController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
	//Route::resource('users', UserController::class);
	Route::resource('users', UsersController::class);
	Route::get('get-data-users-datatables', ['as'=>'get.users','uses'=>'App\Http\Controllers\UsersController@getData']);
	Route::post('users/restore', 'App\Http\Controllers\UsersController@restore')->name('users/restore');
    Route::resource('roles', RoleController::class);
	Route::get('get-data-roles-datatables', ['as'=>'get.roles','uses'=>'App\Http\Controllers\RoleController@getData']);
	Route::post('roles/restore', 'App\Http\Controllers\RoleController@restore')->name('roles/restore');
    Route::resource('permissions', PermissionController::class);
	Route::get('get-data-permissions-datatables', ['as'=>'get.permissions','uses'=>'App\Http\Controllers\PermissionController@getData']);
	Route::post('permissions/restore', 'App\Http\Controllers\PermissionController@restore')->name('permissions/restore');
    Route::resource('posts', PostController::class);
	//Route::resource('reportgneral', ReportsController::class);
	Route::get('report/general', ['as'=>'get.general','uses'=>'App\Http\Controllers\ReportsController@index']);
	Route::post('report/general/download', ['as'=>'get.download','uses'=>'App\Http\Controllers\ReportsController@download']);
	Route::post('generate/general', 'App\Http\Controllers\ReportsController@getData')->name('generate/general');
	
	/**Conteiner Report */
	Route::get('report/containers', [ConteinerReportController::class, 'index'])->name('get.containers.report');
	Route::post('generate/report/containers', ['as'=>'get.reportcontainers','uses'=>'App\Http\Controllers\ConteinerReportController@generateReport']);

	/* Bancos */
	Route::resource('bancos', BancosController::class);
	Route::get('get-data-bancos-datatables', [BancosController::class, 'getData'])->name('get.bancos');

	/* Entidades */
	Route::resource('entidades', EntidadesController::class);
	Route::post('entidades/update',[EntidadesController::class, 'update'])->name('entidades/update');
	Route::get('get-data-entidades-datatables', [EntidadesController::class, 'getData'])->name('get.entidades');

	/* Entidades Banco*/
	Route::resource('entidadbanco', EntidadesBancoController::class);
	Route::get('get-data-entidades-banco-datatables', [EntidadesBancoController::class, 'EntidadesController@getDataBanco'])->name('get.entidades.banco');
	Route::get('get-data-ent-banco-datatables', [EntidadesBancoController::class, 'getDataBancoView'])->name('get.ent.banco');

	/* clasificacion admin */
	Route::resource('clasificaciones', ClasificacionController::class);
	Route::get('get-data-clasificaciones-datatables', [ClasificacionController::class, 'getData'])->name('get.clasificaciones');

	/* contenedores operaciones */
	Route::resource('contenedores', ContenedorController::class);
	Route::get('get-data-contenedores-datatables', [ContenedorController::class, 'getData'])->name('get.contenedores');

	/* puertos operaciones */
	Route::resource('puertos', PuertoController::class);
	Route::get('get-data-puertos-datatables', [PuertoController::class, 'getData'])->name('get.puertos');

	/* catalogo aeropuertos de  operaciones */
	Route::resource('airports', AeropuertoController::class);
	Route::get('get-data-airports-datatables', [AeropuertoController::class, 'getData'])->name('get.airports');

	/* catalogo estados de  operaciones */
	Route::resource('states', EstadoController::class);
	Route::get('get-data-states-datatables', [EstadoController::class, 'getData'])->name('get.states');

	/* operaciones -- operaciones */
	Route::resource('operaciones', OperacionController::class);
	Route::get('get-data-operaciones-datatables', [OperacionController::class, 'getData'])->name('get.operaciones');
	Route::post('operaciones/edit/hbl', [OperacionController::class, 'updateHBL'])->name('operaciones/edit/hbl');

	/*Agregar detalle de contenedor*/
	Route::get('operaciones/dcontainer/{idoperation}/{typeoperation}/{operaciondetail}',[OperacionController::class, 'createdetails'])->name('operaciones.dcontainer');
	Route::post('operaciones/addDetails', [OperacionController::class, 'addDetails'])->name('operaciones/addDetails');
	Route::get('get-data-columns', [OperacionController::class, 'getColumns'])->name('get.columns');
	Route::post('operaciones-puerto',[OperacionController::class, 'puertoSearch']);
	Route::get('autocomplete/fetch', [OperacionController::class, 'puertoSearch'])->name('autocomplete.fetch');
	Route::get('autocomplete/entidad', [OperacionController::class, 'entidadSearch'])->name('autocomplete.entidad');
	Route::post('operaciones-files',[OperacionController::class, 'files']);
	Route::get('operaciones/view/{file}',[OperacionController::class, 'viewFile'])->name('view.file');
	Route::post('operaciones/update/telex', [OperacionController::class, 'telex'])->name('operaciones/update/telex');
	Route::post('operaciones/restore', [OperacionController::class, 'restorePreOperation'])->name('operaciones/restore');


	/** operacion detalle contenedor  **/
	Route::post('operation/container/store',[OperationDetailsController::class, 'store'])->name('container.store');
	Route::post('operation/container/update',[OperationDetailsController::class, 'update'])->name('container.update');
	Route::post('operation/container/delete',[OperationDetailsController::class, 'destroy'])->name('container.delete');
	Route::get('get-data-container-details', [OperationDetailsController::class, 'getData'])->name('get.container.details');
	
	/** Busqueda por contenedor **/
	Route::get('operacion/contenedor/filter',[OperationDetailsController::class, 'search'])->name('operationdetail.filter');
	Route::get('get-containers', [OperationDetailsController::class, 'getContainer'])->name('get.containers');
	Route::get('get-data-container-filter', [OperationDetailsController::class, 'getDataDetails'])->name('get.container.filter');
	
	/** Retornar vacio contenedor **/
	Route::post('operation/container/emptyContainer',[OperationDetailsController::class, 'emptyContainer'])->name('container.emptyContainer');
	Route::post('operation/details/emptyContainer',[OperationDetailsController::class, 'emptyContainer'])->name('operationdetail.emptyContainer');
	Route::get('get-data-operacion-filter', [OperationDetailsController::class, 'getDataDetails'])->name('get.operacion.filter');

	/* cargos admin */
	Route::resource('cargos', CargoController::class);
	Route::get('get-data-cargos-datatables', [CargoController::class, 'getData'])->name('get.cargos');

	/* Portal Acceso a Clientes */
	Route::resource('customer', CustomerController::class);
	Route::get('get-data-customer-datatables', [CustomerController::class, 'getData'])->name('get.customer');
	Route::post('customer/delete', [CustomerController::class, 'delete'])->name('customer/delete');

resources/views/clasificaciones/create.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Clasificaciones<small>Catálogo de Clasificaciones de Entidad</small></h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="{{ url('clasificaciones') }}">Clasificaciones de Entidad</a></li>
        <li class="active">Agregar</li>
    </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

    @if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fa fa-ban"></i> ¡Alerta!</h5>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nueva clasificación</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                {{ Form::open(array('url' => 'clasificaciones')) }}
                <div class="box-body">
                    <div class="form-group">
                        {{ Form::label('nombre', 'Nombre') }}
                        {!! Form::text('nombre', null, [
                        'class' => 'form-control',
                        'required' => 'required',
                        ]) !!}
                    </div>
                </div>
                <div class="box-footer">
                    {{ Form::button('<i class="fa fa-save" aria-hidden="true"></i> Guardar', ['class' => 'btn btn-primary', 'type' => 'submit']) }}
                </div>
                {{ Form::close() }}
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->

    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection

resources/views/clasificaciones/edit.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Clasificaciones<small>Catálogo de Clasificaciones de Entidad</small></h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="{{ url('cargos') }}">Clasificaciones de Entidad</a></li>
        <li class="active">Editar</li>
    </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

    @if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fa fa-ban"></i> ¡Alerta!</h5>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Editar Clasificación <strong>{{$clasificacion->descripcion}}</strong></h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                {{ Form::model($clasificacion, array('route' => array('clasificaciones.update', $clasificacion->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with permission data --}}
                <div class="box-body">
                    <div class="form-group">
                        {{ Form::label('nombre', 'Nombre') }}
                        {!! Form::text('descripcion', null, [
                        'class' => 'form-control',
                        'required' => 'required',
                        ]) !!}
                    </div>
                    
                </div>

                <div class="box-footer">
                    {{ Form::button('<i class="fa fa-refresh" aria-hidden="true"></i> Actualizar', ['class' => 'btn btn-primary', 'type' => 'submit']) }}
                </div>
                {{ Form::close() }}
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->

    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection

resources/views/clasificaciones/index.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Clasificaciones<small>Catálogo de Clasificaciones de Entidad</small></h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Clasificaciones de Entidad</li>
  </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

  @if(session()->has('flash_message'))
  <div class="alert alert-success alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> Éxito!</h4>
    {{ session()->get('flash_message') }}
  </div>
  @endif

  <div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-user"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Clasificaciones </span>
          <span class="info-box-number">{{ $clasificaciones }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-check"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Clasific.  Habilitadas</span>
          <span class="info-box-number">{{ $classificationEnabled }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-trash"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Clasific.  Eliminadas</span>
          <span class="info-box-number">{{ $classificationDisabled }}</span>
          <a href="#" data-filter=".property-sale" class="click"><span>ver Eliminados <i class="fa fa-arrow-circle-right"></i></span></a>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Lista de Clasificaciones </h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="areas-table" class="table table-striped table-bordered dt-responsive"></table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

      @can('Crear')
      <a href="{{ URL::to('clasificaciones/create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Agregar Clasificación </a>
      @endcan
    </div>
    <!-- /.col -->
  </div>

  <!-- Delete Model -->
  <div id="confirmDeleteComment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">

        <!-- header modal -->
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="mySmallModalLabel">Eliminar Clasificación</h4>
        </div>

        <!-- body modal -->
        <div class="modal-body text-center">
          ¿Por favor, confirme que desea eliminar el clasificación: <b><span id="fav-title"></span></b>?
          <hr>
          <form action="{{ route('clasificaciones.destroy','1') }}" id="delForm" method="post">
            {{method_field('delete')}} {{csrf_field()}}
            <input name="id" id="id_emp" type="hidden" />
            <input name="_token" type="hidden" value="{{ csrf_token() }}" />
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            <button type="submit" value="delete" class="btn btn-success">Aceptar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- /.Delete Model -->
</section>

<script>
  $(document).ready(function () {
    // se activa cuando el modal está a punto de ser mostrado.
    $('#confirmDeleteComment').on('show.bs.modal', function (e) {
      var modal = $(this);

      // obtener el atributo idEmpresa del elemento pulsado.
      $("#fav-title").html($(e.relatedTarget).data('title'));
      var idEmpresa = $(e.relatedTarget).data('idemp');
      modal.find('.modal-body #id_emp').val(idEmpresa);
    });
  });

  $(function () {
    $('.click').click(function () {
      $("#example").dataTable().fnDestroy();
      loadTable('0'); 
    });
  });
  
  $(function () {
    loadTable('1');
  });

  function loadTable(eliminados) {
    $('#areas-table').DataTable({
      processing: true,
      serverSide: true,
      destroy: true,
      type: 'GET',
      ajax: "{{ route('get.clasificaciones') }}?showDeleted="+eliminados,
      language: {
        "search": "Buscar",
        "lengthMenu": "Mostar _MENU_ registros por página",
        "zeroRecords": "Lo sentimos, no encontramos lo que estas buscando",
        "info": "Mostrando página _PAGE_ de _PAGES_ de _TOTAL_ Registros",
        "infoEmpty": "Registros no encontrados",
        "infoFiltered": "(Filtrado en _MAX_ registros totales)",
        "paginate": {
          "previous": "Anterior",
          "next": "Siguiente",
        },
      },
      columns: [
        {data: 'DT_RowIndex', name: 'DT_RowIndex', title: '#'},
        { data: 'descripcion', name: 'descripcion', title: 'Descripción' },
        {
          data: 'activo', name: 'activo', title: 'Activo', "render": function (data, type, full, meta) {
            if (data == 1) {
              return '<div class="iradio_flat-green checked" aria-checked="true" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Habilitada';
            } else {
              return '<div class="iradio_flat-green" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Eliminada';
            }
          }
        },
        { data: 'created_at', name: 'created_at', title: 'Creada' },
        { data: 'updated_at', name: 'updated_at', title: 'Actualizada' },
        { data: 'action', name: 'action', title: 'Acciones', orderable: false, searchable: false }
      ]
    });
  }
</script>
</section>
@endsection

resources/views/clasificaciones/show.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Clasificaciones<small>Catálogo de Clasificaciones de Entidad</small></h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li><a href="{{ url('clasificaciones') }}">Clasificaciones de Entidad</a></li>
    <li class="active">Detalle</li>
  </ol>
</section>
<!-- /.Content Header (Page header) -->
<section class="invoice">
  <!-- title row -->
  <div class="row">
    <div class="col-xs-12">
      <h2 class="page-header">
        <i class="fa fa-user"></i> {{ $clasificacion->descripcion }}
        <small class="pull-right">Fecha: {{ \Carbon\Carbon::parse($user->from_date)->format('d/m/Y')}}</small>
      </h2>
    </div>
    <!-- /.col -->
  </div>
  <!-- info row -->
  <div class="row invoice-info">
    <div class="col-sm-4 invoice-col">
      Nombre:
      <address>
        <strong>{{ $clasificacion->descripcion }}</strong><br>
      </address>
    </div>
    
    <div class="col-sm-4 invoice-col">
      <b>Clave #{{ $clasificacion->id }}</b><br>
      <br>
      <b>Fecha de Alta:</b> {{ $clasificacion->created_at }}<br>
      <b>Fecha de Actualización:</b> {{ $clasificacion->updated_at }}<br>
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
  
  </br>
  <!-- this row will not appear when printing -->
  <div class="row no-print">
    <div class="col-xs-12">
      <a href="#" class="btn btn-info" onClick="window.print()"><i class="fa fa-print"></i> Imprimir</a>
    </div>
  </div>
</section>

<!-- Main content -->
<section class="content">




</section>
@endsection