routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\AeropuertoController;
use App\Http\Controllers\BancosController;
use App\Http\Controllers\ClasificacionController;
use App\Http\Controllers\ContenedorController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\EmailsController;
use App\Http\Controllers\EntidadesBancoController;
use App\Http\Controllers\EntidadesController;
use App\Http\Controllers\EstadoController;
use App\Http\Controllers\OperacionController;
use App\Http\Controllers\OperacionDetalleController;
use App\Http\Controllers\OperationDetailsController;
use App\Http\Controllers\PuertoController;
use App\Http\Controllers\CargoController;
use App\Http\Controllers\ConteinerReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Auth::routes([
	'register' => false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('users', UserController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('posts', PostController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
	//Route::resource('users', UserController::class);
	Route::resource('users', UsersController::class);
	Route::get('get-data-users-datatables', ['as'=>'get.users','uses'=>'App\Http\Controllers\UsersController@getData']);
	Route::post('users/restore', 'App\Http\Controllers\UsersController@restore')->name('users/restore');
    Route::resource('roles', RoleController::class);
	Route::get('get-data-roles-datatables', ['as'=>'get.roles','uses'=>'App\Http\Controllers\RoleController@getData']);
	Route::post('roles/restore', 'App\Http\Controllers\RoleController@restore')->name('roles/restore');
    Route::resource('permissions', PermissionController::class);
	Route::get('get-data-permissions-datatables', ['as'=>'get.permissions','uses'=>'App\Http\Controllers\PermissionController@getData']);
	Route::post('permissions/restore', 'App\Http\Controllers\PermissionController@restore')->name('permissions/restore');
    Route::resource('posts', PostController::class);
	//Route::resource('reportgneral', ReportsController::class);
	Route::get('report/general', ['as'=>'get.general','uses'=>'App\Http\Controllers\ReportsController@index']);
	Route::post('report/general/download', ['as'=>'get.download','uses'=>'App\Http\Controllers\ReportsController@download']);
	Route::post('generate/general', 'App\Http\Controllers\ReportsController@getData')->name('generate/general');
	
	/**Conteiner Report */
	Route::get('report/containers', [ConteinerReportController::class, 'index'])->name('get.containers.report');
	Route::post('generate/report/containers', ['as'=>'get.reportcontainers','uses'=>'App\Http\Controllers\ConteinerReportController@generateReport']);

	/* Bancos */
	Route::resource('bancos', BancosController::class);
	Route::get('get-data-bancos-datatables', [BancosController::class, 'getData'])->name('get.bancos');

	/* Entidades */
	Route::resource('entidades', EntidadesController::class);
	Route::post('entidades/update',[EntidadesController::class, 'update'])->name('entidades/update');
	Route::get('get-data-entidades-datatables', [EntidadesController::class, 'getData'])->name('get.entidades');

	/* Entidades Banco*/
	Route::resource('entidadbanco', EntidadesBancoController::class);
	Route::get('get-data-entidades-banco-datatables', [EntidadesBancoController::class, 'EntidadesController@getDataBanco'])->name('get.entidades.banco');
	Route::get('get-data-ent-banco-datatables', [EntidadesBancoController::class, 'getDataBancoView'])->name('get.ent.banco');

	/* clasificacion admin */
	Route::resource('clasificaciones', ClasificacionController::class);
	Route::get('get-data-clasificaciones-datatables', [ClasificacionController::class, 'getData'])->name('get.clasificaciones');

	/* contenedores operaciones */
	Route::resource('contenedores', ContenedorController::class);
	Route::get('get-data-contenedores-datatables', [ContenedorController::class, 'getData'])->name('get.contenedores');

	/* puertos operaciones */
	Route::resource('puertos', PuertoController::class);
	Route::get('get-data-puertos-datatables', [PuertoController::class, 'getData'])->name('get.puertos');

	/* catalogo aeropuertos de  operaciones */
	Route::resource('airports', AeropuertoController::class);
	Route::get('get-data-airports-datatables', [AeropuertoController::class, 'getData'])->name('get.airports');

	/* catalogo estados de  operaciones */
	Route::resource('states', EstadoController::class);
	Route::get('get-data-states-datatables', [EstadoController::class, 'getData'])->name('get.states');

	/* operaciones -- operaciones */
	Route::resource('operaciones', OperacionController::class);
	Route::get('get-data-operaciones-datatables', [OperacionController::class, 'getData'])->name('get.operaciones');
	Route::post('operaciones/edit/hbl', [OperacionController::class, 'updateHBL'])->name('operaciones/edit/hbl');

	/*Agregar detalle de contenedor*/
	Route::get('operaciones/dcontainer/{idoperation}/{typeoperation}/{operaciondetail}',[OperacionController::class, 'createdetails'])->name('operaciones.dcontainer');
	Route::post('operaciones/addDetails', [OperacionController::class, 'addDetails'])->name('operaciones/addDetails');
	Route::get('get-data-columns', [OperacionController::class, 'getColumns'])->name('get.columns');
	Route::post('operaciones-puerto',[OperacionController::class, 'puertoSearch']);
	Route::get('autocomplete/fetch', [OperacionController::class, 'puertoSearch'])->name('autocomplete.fetch');
	Route::get('autocomplete/entidad', [OperacionController::class, 'entidadSearch'])->name('autocomplete.entidad');
	Route::post('operaciones-files',[OperacionController::class, 'files']);
	Route::get('operaciones/view/{file}',[OperacionController::class, 'viewFile'])->name('view.file');
	Route::post('operaciones/update/telex', [OperacionController::class, 'telex'])->name('operaciones/update/telex');
	Route::post('operaciones/restore', [OperacionController::class, 'restorePreOperation'])->name('operaciones/restore');


	/** operacion detalle contenedor  **/
	Route::post('operation/container/store',[OperationDetailsController::class, 'store'])->name('container.store');
	Route::post('operation/container/update',[OperationDetailsController::class, 'update'])->name('container.update');
	Route::post('operation/container/delete',[OperationDetailsController::class, 'destroy'])->name('container.delete');
	Route::get('get-data-container-details', [OperationDetailsController::class, 'getData'])->name('get.container.details');
	
	/** Busqueda por contenedor **/
	Route::get('operacion/contenedor/filter',[OperationDetailsController::class, 'search'])->name('operationdetail.filter');
	Route::get('get-containers', [OperationDetailsController::class, 'getContainer'])->name('get.containers');
	Route::get('get-data-container-filter', [OperationDetailsController::class, 'getDataDetails'])->name('get.container.filter');
	
	/** Retornar vacio contenedor **/
	Route::post('operation/container/emptyContainer',[OperationDetailsController::class, 'emptyContainer'])->name('container.emptyContainer');
	Route::post('operation/details/emptyContainer',[OperationDetailsController::class, 'emptyContainer'])->name('operationdetail.emptyContainer');
	Route::get('get-data-operacion-filter', [OperationDetailsController::class, 'getDataDetails'])->name('get.operacion.filter');

	/* cargos admin */
	Route::resource('cargos', CargoController::class);
	Route::get('get-data-cargos-datatables', [CargoController::class, 'getData'])->name('get.cargos');

	/* Portal Acceso a Clientes */
	Route::resource('customer', CustomerController::class);

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/create.blade.php
@extends('adminlte::layouts.app')
<link href="{{ URL::asset('/css/bootstrap-tagsinput.css') }}" rel="stylesheet" type="text/css" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.15/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
	<h1>Add Customer<small>Access</small></h1>
     <ol class="breadcrumb">
        <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="{{ url('customer') }}">Access to Customer Portal</a></li>
        <li class="active">Add</li>
    </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

    @if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fa fa-ban"></i> ¡Alerta!</h5>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
    </div>
    @endif
    <div class="alert alert-danger" role="alert" style="display:none;" id="error">
        <ul id="error"></ul>
    </div>
    <div class="alert alert-success" role="alert" style="display:none;" id="exito">
        
    </div>


      <div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Customer Access</h3>
              <p>The fields marked with <b>*</b> are required</p>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form id="create" method="POST" action= '{{ action("CustomerController@add") }}'>
 <div class="box-body">
 {{csrf_field()}}
    <div class="col-md-6">
        <div class="form-group">
            {{ Form::label('email', 'Email * ') }}
            <div class="col-md-12 field_wrapper">
                <div class="col-md-10">
                    <input type="text" name="email[]" class="form-control"  requerid value=""/>
                </div>
                <div class="col-md-2">
                    <a href="javascript:void(0);" class="add_button btn btn-primary" title="Add field"><i class="fa fa-plus" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {{ Form::label('customer', 'Customer') }}
            <input id="consignee_desc" name="name" value="{{old('name')}}" requerid type="text" class="form-control" placeholder="Search Customer" />
                        <input type="hidden" id="custom" name="custom" requerid >
            
        </div>
    </div>
    
    

    


    
    
      </div>

 <div class="box-footer">
    {{ Form::button('<i class="fa fa-save" aria-hidden="true"></i> Guardar', ['class' => 'btn btn-primary', 'type' => 'submit']) }}

    </div>

    </form>

            
          </div>
          <!-- /.box -->

        

        


        </div>
        <!--/.col (left) -->
       
      </div>
      <!-- /.row -->
</section>
<!-- /.content -->


@endsection
@yield('content')
@section('scripts')
<script type="text/javascript">
    $(document).ready(function(){

        var maxField = 10; //Input fields increment limitation
        var addButton = $('.add_button'); //Add button selector
        var wrapper = $('.field_wrapper'); //Input field wrapper
        var fieldHTML = '<div class="col-md-12" style="display: flex;"><input type="text" name="email[]" class="form-control"  requerid="requerid" value=""/ style="width: 82%;"> <a href="javascript:void(0);" class="remove_button btn btn-primary" title="Remove field" style="margin-left: 32px;"><i class="fa fa-times" aria-hidden="true"></i></a></div>'; //New input field html 
        var x = 1; //Initial field counter is 1
        $(addButton).click(function(){ //Once add button is clicked
            if(x < maxField){ //Check maximum number of input fields
                x++; //Increment field counter
                $(wrapper).append(fieldHTML); // Add field html
            }
        });
        $(wrapper).on('click', '.remove_button', function(e){ //Once remove button is clicked
            e.preventDefault();
            $(this).parent('div').remove(); //Remove field html
            x--; //Decrement field counter
        });

        
            function entidadSearch(tipo,etiqueta){
            $("#"+etiqueta).easyAutocomplete({
                url: function(search) {
                    return "{{route('autocomplete.entidad')}}?tipo=consignee&search=" + search;
                },
            
                getValue: "nombre",
                list: {
                        onSelectItemEvent: function() {
                            var dataID = $("#"+etiqueta).getSelectedItemData().id;
                            $("#"+tipo).val(dataID);
                        },
                match: {
                        enabled: true
                        }
                }
            });
        }

        $('#consignee_desc').ready(function(){
            entidadSearch("custom", "consignee_desc");
        });
    });
</script> 

   
@stop
@yield('scripts')

resources/views/customer/index.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Access <small>to Customer Portal</small></h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Access to Customer Portal</li>
  </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

  @if(session()->has('flash_message'))
  <div class="alert alert-success alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> success!</h4>
    {{ session()->get('flash_message') }}
  </div>
  @endif

  <div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="fa fa-users"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Customer Totales</span>
          <span class="info-box-number">
            <h3>{{ $users['TotalUser'] }}</h3>
          </span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="fa fa-user-plus"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Customer Enable</span>
          <span class="info-box-number">
            <h3>{{ $users['UserEnable'] }}</h3>
          </span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    
  </div>
  <!-- /.row -->



  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Customer List</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="alert alert-danger" role="alert" style="display:none;" id="error">
              <ul id="error"></ul>
          </div>
          <div class="alert alert-success" role="alert" style="display:none;" id="exito">
              
          </div>
          <table id="usuarios-table" class="table table-striped table-bordered dt-responsive nowrap"></table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
      <a href="{{ route('customer.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Add Customer Access</a>
    </div>
    <!-- /.col -->
  </div>

  <!-- Delete Model -->
  <div id="confirmDeleteComment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">

        <!-- header modal -->
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="mySmallModalLabel">Customer Disable</h4>
        </div>

        <!-- body modal -->
        <div class="modal-body text-center">
          ¿Please confirm that you want to delete the user: <b><span id="fav-title"></span></b>?
          <hr>
          <form action='{{ action("CustomerController@delete") }}' id="delForm" method="post">
          {{csrf_field()}}
            <input name="id_user" id="id_user" type="hidden" />
            <input name="_token" type="hidden" value="{{ csrf_token() }}" />
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <button type="submit" value="delete" class="btn btn-success">Accept</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- /.Delete Model -->
</section>

<script type="text/javascript">
  $(document).ready(function () {
    // se activa cuando el modal está a punto de ser mostrado.
    $('#confirmDeleteComment').on('show.bs.modal', function (e) {
      var modal = $(this);

      // obtener el atributo idEmpresa del elemento pulsado.
      $("#fav-title").html($(e.relatedTarget).data('title'));
      var idEmpresa = $(e.relatedTarget).data('idemp');
      console.log(idEmpresa);
      modal.find('.modal-body #id_user').val(idEmpresa);
    });

  

  });

  
  $(function () {
    $('#usuarios-table').DataTable({
      processing: true,
      serverSide: true,
      type: 'GET',
      ajax: "{{ route('get.customer') }}",
      language: {
        "search": "Buscar",
        "lengthMenu": "Mostar _MENU_ registros por página",
        "zeroRecords": "Lo sentimos, no encontramos lo que estas buscando",
        "info": "Mostrando página _PAGE_ de _PAGES_ de _TOTAL_ Registros",
        "infoEmpty": "Registros no encontrados",
        "infoFiltered": "(Filtrado en _MAX_ registros totales)",
        "paginate": {
          "previous": "Anterior",
          "next": "Siguiente",
        },
      },
      columns: [
        { data: 'id', name: 'id', title: '#' },
        { data: 'name', name: 'name', title: 'Name' },
        { data: 'email', name: 'email', title: 'Email' },
        { data: 'consignee', name: 'consignee', title: 'Consignee' },
        { data: 'created_at', name: 'created_at', title: 'Created' },
        {
          data: 'status', name: 'status', title: 'Status', "render": function (data, type, full, meta) {
            if (data == 1) {
              return '<div class="iradio_flat-green checked" aria-checked="true" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Enabled';
            }else {
              return '<div class="iradio_flat-green" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Deleted';
            }
          }
        },
        { data: 'action', name: 'action', title: 'Acciones', orderable: false, searchable: false }
      ]
    });
  });
</script>

@endsection